#+
# $Id: Makefile.BeOS 1.3 1998/07/05 10:08:24 alpern Exp $
#-

TOP = ../..
include $(TOP)/make/beos-r4-gcc

ALL_SRCS 	= $(LCD_SRCS) $(LCD_BE_SRCS)
LCD_OBJS 	= $(patsubst %.cxx,$(OBJDIR)/%.o,$(LCD_SRCS))
LCD_BE_OBJS 	= $(patsubst %.cxx,$(OBJDIR)/%.o,$(LCD_BE_SRCS))

all:	libs
libs:	MtxOrb.so MtxOrbBe.so
exes:

MtxOrb.so:	$(LCD_OBJS)
	$(LINK_SHARED) -o $@ $<

MtxOrbBe.so:	$(LCD_BE_OBJS)
	$(LINK_SHARED) -o $@ $<
